version: '2'

services:
  shortener:
    build: .
    image: shortener
    depends_on:
      - tarantool
    networks:
      - shortener_net

  nginx:
    image: nginx:stable
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/shortener.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - shortener
    networks:
      - shortener_net

  tarantool:
    build:
      context: ./docker/tarantool
    image: shortener-tarantool
    environment:
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "G9YuMsd"
    networks:
      - shortener_net

networks:
  shortener_net:
    driver: bridge
