version: '2'

services:
  tarantool-master:
    build:
      context: ./docker/tarantool/master
    image: shortener-tarantool-master
    environment:
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "G9YuMsd"
    networks:
      - shortener_net

  tarantool-replica:
    build:
      context: ./docker/tarantool/replica
    image: shortener-tarantool-replica
    environment:
      TARANTOOL_USER_NAME: "admin"
      TARANTOOL_USER_PASSWORD: "G9YuMsd"
    networks:
      - shortener_net

  app:
    build: .
    image: shortener
    depends_on:
      - tarantool-master
    networks:
      - shortener_net

  nginx:
    image: nginx:stable
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - shortener_net

networks:
  shortener_net:
    driver: bridge
