---

keep_in_sec: 604800

logging:
  level: 'debug'
  format: '%(asctime)-15s %(levelname)-8s %(message)s'

tarantool:
  host: 'tarantool'
  port: 3301
  user: 'tarantool'
  password: 'kdCm!u=8As396FF4'
  space: 'shortener'
